### PR TITLE
add postinstall with rc.local execut after reboot system

### PR DESCRIPTION
**Pull request by jua74470**
add postinstall with rc.local execut after reboot system

minimal postinstall just install system update

### CODE REVIEW

**Comment by jua74470** [comment]
sorry I forgot you have to reboot the system and not stop it it's a mistake you made

after installing a new system you have to restart on it and turn off the computer otherwise there is no point

**Comment by YasuhiroABE** [comment]
Hi, 

I don't need to shutdown the system, but some of UFI implementation cannot change the boot order during its installation process.
It means the installation process will continue endlessly. 
So, the setting is for safety.

The default systemd package already has the rc-loca.service file.
So, you just put your rc.local script on the /etc/rc.local and invoke the "systemctl enable rc-local" command at the late-commands sectrion.

**Comment by jua74470** [comment]
so for your information the rc-local.service file that is included in system is not even the code that is inside and the one that is included by default in systemd and bugger once activated it crashes the system and it does not even start which forces you to switch to rescue mode to deactivate it so you have to replace it without that the computer does not start this is a problem that is present in system for several years and which has never been corrected in the code

as for the uefi to not have this problem you have 2 solutions either leave your hard drive as the default boot system and temporarily boot on the boot of your installation (cd player, usb etc)

generally in the setup of your bios via esc, del or F2
you put your hard drive as the default boot system

then either you have in the setup a menu that allows you to temporarily boot on the cd or usb player

or it is the key F10 or F12 (often F12 is the pxe boot but not always)

or if your bios does not have this function add a timeout in the grub/isolinux menu of the installation

and a first boot line configured by default to boot on the hard disk and place the installer boot line in second position

but you should never use the poweroof and shutdown -h commands in an automated way

because this causes the machine to stop, but now even network installations work with the iso file and you should never stop a server because this requires manual intervention to restart it, which is billed by the hosting

**Comment by YasuhiroABE** [comment]
OK. Regarding the rc-local.service, the "[Install]" section is essential to start it.
* [https://www.linuxbabe.com/linux-server/how-to-enable-etcrc-local-with-systemd](https://www.linuxbabe.com/linux-server/how-to-enable-etcrc-local-with-systemd)

If your purpose is only to apply the latest packages, the "updates: all" setting should be enough to achieve your goal.
* [https://canonical-subiquity.readthedocs-hosted.com/en/latest/reference/autoinstall-reference.html#updates](https://canonical-subiquity.readthedocs-hosted.com/en/latest/reference/autoinstall-reference.html#updates)

The following is an alternative patch for the user-data file, for example.

```
diff --git a/config/user-data.efi b/config/user-data.efi
index dc9942e..ad3b867 100644
--- a/config/user-data.efi
+++ b/config/user-data.efi
@@ -83,5 +83,11 @@ autoinstall:
     install-server: true
     allow-pw: true
     authorized-keys: []
+  updates: all
   late-commands:
     - cp /cdrom/ubuntu.sudoers /target/etc/sudoers.d/99-user-ubuntu
+    - echo '\n[Install]\nWantedBy=multi-user.target\nWantedBy=network-online.service\n' >> /target/usr/lib/systemd/system/rc-local.service
+    - echo '#!/bin/bash\n\necho $(date) some other tasks here > /tmp/rc.local.txt\n' > /target/etc/rc.local
+    - chmod +x /target/etc/rc.local
+    - curtin in-target --target=/target -- systemctl daemon-reload
+    - curtin in-target --target=/target -- systemctl enable rc-local.service
```

Thank you for proposing some workarounds; unfortunately, these are unsuitable in my use case.
I agree that for some of the IaaS or latest computing environments, your "shutdown: reboot" setting might be sufficient.
However, they don't align with the goals and use cases I have in mind for this project.

I hope that you enjoy developing your forked version to suit your vision.

**Comment by jua74470** [comment]
my reason was mainly to allow everyone to be able to run a post-installation script to personalize the system

and I made sure that it only runs once

and that it is minimal with only updates in order to allow everyone to be able to personalize it

and I also made sure to test the code under proxmox before sending you this pull request

**Pull request closed without merging**
